# Generated by Django 2.2.6 on 2019-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordetail',
            name='install_date',
            field=models.DateField(),
        ),
    ]
