# Generated by Django 2.2.6 on 2019-10-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20191009_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordetail',
            options={'ordering': ['sensor_name']},
        ),
        migrations.AlterField(
            model_name='sensordetail',
            name='sensor_name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
